# Generated by Django 4.2 on 2026-07-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_release_rollout_default'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingcommand',
            new_name='commands_pe_compute_77b00a_idx',
            old_name='commands_pe_compute_idx',
        ),
        migrations.AlterField(
            model_name='release',
            name='manifest',
            field=models.JSONField(blank=True, default=dict, help_text="Avtomatik: {'deleted_files': [...], 'total_files': N, 'total_size': N}"),
        ),
        migrations.AlterField(
            model_name='updatefile',
            name='rel_path',
            field=models.CharField(help_text="Agent papkasidagi nisbiy yo'l, masalan: 'Nigoh.exe'", max_length=255),
        ),
        migrations.AlterField(
            model_name='updatefile',
            name='sha256',
            field=models.CharField(blank=True, help_text='Avtomatik hisoblanadi', max_length=64),
        ),
    ]
