# Generated by Django 4.2 on 2026-04-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='last_boot_time',
        ),
    ]
