# Generated by Django 4.2 on 2026-04-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_remove_computer_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.AddField(
            model_name='group',
            name='building',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], null=True, verbose_name='Bino'),
        ),
        migrations.AddField(
            model_name='group',
            name='floor',
            field=models.IntegerField(choices=[(-1, 'Pastki qavat'), (1, '1-qavat'), (2, '2-qavat'), (3, '3-qavat'), (4, '4-qavat')], null=True, verbose_name='Qavat'),
        ),
        migrations.AddField(
            model_name='group',
            name='room_number',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
