# Generated by Django 4.2 on 2026-06-29 13:10

from django.db import migrations, models
import endpoints.models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_device_id_and_versioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='auth_token',
            field=models.CharField(blank=True, default=endpoints.models._gen_auth_token, help_text='Kelajakda agent uchun xavfsizlik tokeni (hozir ixtiyoriy)', max_length=64, null=True, unique=True),
        ),
    ]
