# Generated by Django 4.2 on 2026-03-22 07:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Masalan: 'Steam o'yinlari' yoki 'Telegram'", max_length=150, unique=True)),
                ('match_type', models.CharField(choices=[('PROCESS', "O'zining nomi (Masalan: csgo.exe)"), ('PARENT', 'Ota jarayoni nomi (Masalan: steam.exe)')], default='PROCESS', max_length=10)),
                ('default_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('blocked_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockedURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_address', models.CharField(db_index=True, max_length=255, unique=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessAlertLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(max_length=255)),
                ('full_path', models.TextField()),
                ('attempts_count', models.PositiveIntegerField(default=1)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_alerts', to='endpoints.computer')),
                ('process_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracking.blockedprocess')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockedAttemptLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempts_count', models.PositiveIntegerField(default=1)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_attempts', to='endpoints.computer')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tracking.blockedurl')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('url', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='endpoints.computer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
