# Generated by Django 4.2 on 2026-03-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedprocess',
            name='default_reason',
        ),
        migrations.AddField(
            model_name='blockedprocess',
            name='description',
            field=models.TextField(blank=True, help_text='Nima sababdan taqiqlangani haqida izoh', null=True),
        ),
        migrations.AlterField(
            model_name='blockedprocess',
            name='match_type',
            field=models.CharField(choices=[('PROCESS', "O'zining nomi (Masalan: csgo)"), ('PARENT', 'Ota jarayoni nomi (Masalan: steam)')], default='PROCESS', max_length=10),
        ),
        migrations.AlterField(
            model_name='blockedprocess',
            name='name',
            field=models.CharField(help_text="Dastur nomi (.exe yozish shart emas), masalan: 'telegram'", max_length=150, unique=True),
        ),
    ]
