# Generated by Django 4.2 on 2026-03-22 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
        ('tracking', '0002_remove_blockedprocess_default_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsageStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('total_open_seconds', models.PositiveIntegerField(default=0, help_text='Umumiy ochiq turgan vaqt')),
                ('active_seconds', models.PositiveIntegerField(default=0, help_text="Sof aktiv bo'lgan (fokusdagi) vaqt")),
                ('mouse_active_seconds', models.PositiveIntegerField(default=0, help_text='Sichqoncha qimirlagan vaqt')),
                ('keyboard_active_seconds', models.PositiveIntegerField(default=0, help_text='Klaviatura bosilgan vaqt')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usages', to='endpoints.computer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
