# Generated by Django 4.2 on 2026-04-05 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_remove_computer_ip_address_and_more'),
        ('tracking', '0003_appusagestatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenShareSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_duration', models.PositiveIntegerField(default=300)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda (Agentga xabar ketdi)'), ('ACTIVE', 'Faol (Agent URL yubordi)'), ('CLOSED', 'Yopilgan / Yakunlangan')], default='PENDING', max_length=20)),
                ('stream_url', models.URLField(blank=True, max_length=500, null=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_sessions', to='endpoints.computer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
