# Generated by Django 4.2 on 2026-04-06 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_remove_computer_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0004_screensharesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastComputer',
            fields=[
            ],
            options={
                'verbose_name': 'Ekranni Tarqatish (Broadcast)',
                'verbose_name_plural': 'Ekranni Tarqatish (Broadcast)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('endpoints.computer',),
        ),
        migrations.CreateModel(
            name='RemoteControlSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveIntegerField(default=300)),
                ('stream_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_sessions', to=settings.AUTH_USER_MODEL)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_sessions', to='endpoints.computer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
