# Generated by Django 4.2 on 2026-04-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_broadcastcomputer_remotecontrolsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedprocess',
            name='match_type',
            field=models.CharField(choices=[('PROCESS', "O'zining nomi"), ('PARENT', 'Ota jarayoni nomi')], default='PROCESS', max_length=10),
        ),
        migrations.AlterField(
            model_name='remotecontrolsession',
            name='stream_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
