# Generated by Django 4.2 on 2026-07-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alter_blockedprocess_match_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusagestatistic',
            name='full_path',
            field=models.CharField(blank=True, help_text="Exe faylning to'liq yo'li", max_length=500, null=True),
        ),
    ]
