# Generated by Django 4.2 on 2026-07-01 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tracking.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_alter_computer_auth_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0007_appusagestatistic_full_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('DELIVERED', 'Agent qabul qildi'), ('COMPLETED', 'Rasm keldi'), ('FAILED', 'Xato')], default='PENDING', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Agent tomonidan yuborilgan screenshot', null=True, upload_to=tracking.models._screenshot_upload_path)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Agent qabul qilgan vaqt', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Rasm yuklangan vaqt', null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_requests', to='endpoints.computer')),
                ('requested_by', models.ForeignKey(blank=True, help_text="Qaysi admin so'ragan (audit uchun)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshot_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveIntegerField(default=1800, help_text='Sessiya davomiyligi (sek)')),
                ('stream_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda (input URL yubormagan)'), ('ACTIVE', 'Faol (barcha output URL oldi)'), ('CLOSED', 'Yakunlangan'), ('FAILED', 'Xato')], default='PENDING', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_sessions', to=settings.AUTH_USER_MODEL)),
                ('input_computer', models.ForeignKey(help_text='Ekranini uzatuvchi PC (screen_share.exe shu yerda ishga tushadi)', on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_as_input', to='endpoints.computer')),
                ('output_computers', models.ManyToManyField(blank=True, help_text="Ekranni ko'rsatuvchi PClar (brauzerdan URL'ga o'tishadi)", related_name='broadcast_as_output', to='endpoints.computer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='screenshotrequest',
            index=models.Index(fields=['computer', '-created_at'], name='tracking_sc_compute_8a3f2d_idx'),
        ),
    ]
